// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8e4jhCrgmT1bMulUCq6QxKG8uN8-pnFY',
    appId: '1:187905642713:web:fdc803cf869dd099702ec8',
    messagingSenderId: '187905642713',
    projectId: 'fir-kaylasoft',
    authDomain: 'fir-kaylasoft.firebaseapp.com',
    storageBucket: 'fir-kaylasoft.appspot.com',
    measurementId: 'G-Z5M5H675M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-f51cFXVVP-RG86LM6wCWNXZdw8U8bs',
    appId: '1:187905642713:android:d47fc0d9b41eb320702ec8',
    messagingSenderId: '187905642713',
    projectId: 'fir-kaylasoft',
    storageBucket: 'fir-kaylasoft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCURzd8uCIJax1ZypVC7JPMTqrHYiihU68',
    appId: '1:187905642713:ios:dd568ad5e671910f702ec8',
    messagingSenderId: '187905642713',
    projectId: 'fir-kaylasoft',
    storageBucket: 'fir-kaylasoft.appspot.com',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCURzd8uCIJax1ZypVC7JPMTqrHYiihU68',
    appId: '1:187905642713:ios:190c1e750ec74c05702ec8',
    messagingSenderId: '187905642713',
    projectId: 'fir-kaylasoft',
    storageBucket: 'fir-kaylasoft.appspot.com',
    iosBundleId: 'com.example.studentManagement.RunnerTests',
  );
}
